spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    hikari:
      auto-commit: true
      maximum-pool-size: 10 # connections = ((cpu \u6838\u5FC3\u6570 *2) + \u78C1\u76D8\u6570\u91CF) \u8FD1\u4F3C\u503C\u3002\u9ED8\u8BA410
      connection-test-query: select 1 # \u83B7\u53D6\u8FDE\u63A5\u65F6\uFF0C\u68C0\u6D4B\u8BED\u53E5

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
